### ISSUE TITLE
Monitor Configuration window not shown at startup in Linux

### ISSUE THREAD

**Issue by mohsendb7008** [Chillin-Examples/Pacman#1]
Hello, I was trying to run Chilin Monitor and reload a played game, but it seems that monitor is stuck with the full screen mode since I couldn't see the settings page at the monitor startup! Please help me change the monitor size and resolution on my debian based operating system.

**Comment by M6stafa** [comment]
First remove the bundles to to reduce the size of file that you must edit.

open `~/.config/unity3d/Koala/Chillin Monitor 2/prefs` with a text editor. find the `<pref name="Screenmanager Fullscreen mode" type="int">` and change its value to `3`. `3` means Windowed.

you can also change the UnityGraphicsQuality and resolution.
for `UnityGraphicsQuality`, the higher value means better quality and its max is `5`. the `3` is a good value for this.

for resolution:
```
<pref name="Screenmanager Resolution Height" type="int">900</pref>
<pref name="Screenmanager Resolution Width" type="int">1600</pref>
```
set these two values, keep the resolution at `16:9` ratio.
