### ISSUE TITLE
run nashodan cpp dar qt dar windows

### ISSUE THREAD

**Issue by ahak14** [Chillin-Examples/Pacman#3]
salam.
vaghti icon mosallas e sabz ro mizanam dar qt ye cmd baz mishe va matne zir namayesh dade mishe:

>>> Connecting to host 'localhost' port 5000 ...
[0;31m>>> Failed to connect: Unknown error[0m
>>> Reconnecting in 1 seconds ...
>>> Connecting to host 'localhost' port 5000 ...
[0;31m>>> Failed to connect: Unknown error[0m
>>> Reconnecting in 1 seconds ...
>>> Connecting to host 'localhost' port 5000 ...
[0;31m>>> Failed to connect: Unknown error[0m
>>> Reconnecting in 1 seconds ...
>>> Connecting to host 'localhost' port 5000 ...
[0;31m>>> Failed to connect: Unknown error[0m
>>> Reconnecting in 1 seconds ...
>>> Connecting to host 'localhost' port 5000 ...
[0;31m>>> Failed to connect: Unknown error[0m
Press <RETURN> to close this window...

baraye python ham emtehan kardam dorost javab dad.
yani python server va random va python client ro ejra karam va tooye monitor bazi ro neshoon dad vali cpp ro ke mikham ejra konam oon error ro mide va tooye monitor team pacman namayesh dade nemishe.

**Comment by AminHP** [comment]
file haye marboot be ssl ro motabeqe doc e setup copy kardin?
baqie mavarede doc ro eynan anjam dadin?

**Comment by ahak14** [comment]
Mamnoon dorost shod

**Comment by ahak14** [comment]
Moteassefane dobare hamin joori shod
Oon dafe ssl ro dakhel qt rikhtam dorost shod ama alan ke code AI ro taghir dadam bazam hamoon error oomad
